name: 'Giphy PR Comment'
description: 'Add a Giphy GIF comment to a pull request'
inputs:
  github-token:  # id of input
    description: 'Github Token'
    required: true
  giphy-api-key:
    description: 'Giphy API Key'
    required: true
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gihub-token }}
    - ${{ inputs.giphy-api-key }}